package com.nexus.contract.provider;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import com.nexus.AbstractIntegrationTest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.Bean;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.web.SecurityFilterChain;

/**
 * Provider-side Pact verification.
 * Reads pact files from target/pacts/ (generated by consumer tests) and verifies
 * each interaction against the real running Spring Boot app (via Testcontainers).
 */
@Provider("nexus-admin-api")
@PactFolder("target/pacts")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class NexusPactProviderTest extends AbstractIntegrationTest {

    private static final String TENANT_ID = "00000000-0000-0000-0000-000000000001";
    private static final String ROUTE_ID  = "00000000-0000-0000-0000-000000000002";

    // Disable Spring Security so provider tests aren't blocked by auth.
    // Auth correctness is covered by AuthFilterTest; here we test API contracts.
    // @Order(1) ensures this chain takes priority over the main SecurityConfig chain.
    @TestConfiguration
    static class NoSecurityConfig {
        @Bean
        @Order(1)
        SecurityFilterChain testChain(HttpSecurity http) throws Exception {
            http.csrf(AbstractHttpConfigurer::disable)
                .authorizeHttpRequests(auth -> auth.anyRequest().permitAll());
            return http.build();
        }
    }

    @LocalServerPort
    private int port;

    @Autowired
    private JdbcTemplate jdbc;

    @BeforeEach
    void setupTarget(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPact(PactVerificationContext context) {
        context.verifyInteraction();
    }

    @State("admin user is authenticated")
    void adminAuthenticated() {
        // In-memory admin user is always present — no setup needed.
    }

    @State("tenant with id 00000000-0000-0000-0000-000000000001 exists")
    void tenantExists() {
        jdbc.update("""
                INSERT INTO tenants (id, name, slug, plan, status, created_at)
                VALUES (?::uuid, 'Pact Tenant', 'pact-tenant', 'FREE', 'ACTIVE', NOW())
                ON CONFLICT (id) DO NOTHING
                """, TENANT_ID);
    }

    @State("tenant with id 00000000-0000-0000-0000-000000000001 has route 00000000-0000-0000-0000-000000000002")
    void tenantAndRouteExist() {
        jdbc.update("""
                INSERT INTO tenants (id, name, slug, plan, status, created_at)
                VALUES (?::uuid, 'Pact Route Tenant', 'pact-route-tenant', 'FREE', 'ACTIVE', NOW())
                ON CONFLICT (id) DO NOTHING
                """, TENANT_ID);
        jdbc.update("""
                INSERT INTO routes (id, tenant_id, path_pattern, target_url, method, strip_prefix, auth_type, retry_attempts, active)
                VALUES (?::uuid, ?::uuid, '/api/**', 'http://backend', 'ANY', false, 'NONE', 0, true)
                ON CONFLICT (id) DO NOTHING
                """, ROUTE_ID, TENANT_ID);
    }
}
